# Generated by Django 4.0.5 on 2022-07-05 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TableWorks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_user', models.CharField(max_length=50, verbose_name='ID заказа')),
                ('works', models.CharField(max_length=50, verbose_name='Вид заказа')),
                ('themes', models.CharField(max_length=250, verbose_name='Тема заказа')),
                ('days', models.CharField(max_length=50, verbose_name='Срок выполнения заказа')),
                ('origins', models.CharField(max_length=50, verbose_name='Оригинальность работы')),
                ('plus_func', models.TextField(verbose_name='Дополнительная информация')),
                ('money', models.CharField(max_length=50, verbose_name='Стоимость работы')),
            ],
        ),
    ]
