# Generated by Django 4.0.6 on 2022-07-24 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgBots', '0002_remove_tableworks_money'),
    ]

    operations = [
        migrations.AddField(
            model_name='tableworks',
            name='url_name',
            field=models.CharField(default=None, max_length=50, verbose_name='Ссылка на скачивание'),
            preserve_default=False,
        ),
    ]
